In [10]:
import pandas as pd

In [11]:
path1 = "Tabela5-sem_emprego_2012.csv"
path2 = "Tabela5-sem_emprego_2026.csv"
path3 = "Tabela 1.1.1.xls"

In [12]:
Tabela_regiao = pd.read_excel(path3,header=None)

In [13]:
Sem_emprego_2012= pd.read_csv(path1, sep=";", skiprows=0, decimal=",", encoding="UTF-8")

In [14]:
Sem_emprego_2026= pd.read_csv(path2, sep=";", skiprows=0, decimal=",", encoding="UTF-8")

In [15]:
Sem_emprego_2026 = Sem_emprego_2026.dropna(axis=1,how="all")
Sem_emprego_2012 = Sem_emprego_2012.dropna(axis=1,how="all")

# Teste tabela 2012

In [16]:
Sem_emprego_2012

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,45.3,54.7
1,AL,27,Alagoas,44.7,55.3
2,AM,13,Amazonas,47.5,52.5
3,AP,16,Amapá,48.1,51.9
4,BA,29,Bahia,43.8,56.2
5,CE,23,Ceará,51.1,48.9
6,DF,53,Distrito Federal,41.0,59.0
7,ES,32,Espírito Santo,46.4,53.6
8,GO,52,Goiás,41.0,59.0
9,MA,21,Maranhão,47.2,52.8
10,MG,31,Minas Gerais,43.1,56.9
11,MS,50,Mato Grosso do Sul,47.2,52.8
12,MT,51,Mato Grosso,44.1,55.9
13,PA,15,Pará,43.2,56.8
14,PB,25,Paraíba,44.4,55.6
15,PE,26,Pernambuco,43.9,56.1
16,PI,22,Piauí,51.2,48.8
17,PR,41,Paraná,40.3,59.7
18,RJ,33,Rio de Janeiro,44.2,55.8
19,RN,24,Rio Grande do Norte,51.0,49.0
20,RO,11,Rondônia,43.4,56.6
21,RR,14,Roraima,41.8,58.2
22,RS,43,Rio Grande do Sul,42.8,57.2
23,SC,42,Santa Catarina,42.7,57.3
24,SE,28,Sergipe,46.5,53.5
25,SP,35,São Paulo,45.4,54.6
26,TO,17,Tocantins,55.3,44.7

# Teste tabela 2026

In [17]:
Sem_emprego_2026

,Sigla,Código,Estado,Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,53.2,46.8
1,AL,27,Alagoas,50.7,49.3
2,AM,13,Amazonas,46.8,53.2
3,AP,16,Amapá,51.1,48.9
4,BA,29,Bahia,44.7,55.3
5,CE,23,Ceará,52.7,47.3
6,DF,53,Distrito Federal,47.9,52.1
7,ES,32,Espírito Santo,47.5,52.5
8,GO,52,Goiás,47.5,52.5
9,MA,21,Maranhão,49.1,50.9
10,MG,31,Minas Gerais,48.6,51.4
11,MS,50,Mato Grosso do Sul,45.3,54.7
12,MT,51,Mato Grosso,42.8,57.2
13,PA,15,Pará,48.3,51.7
14,PB,25,Paraíba,48.9,51.1
15,PE,26,Pernambuco,48.7,51.3
16,PI,22,Piauí,55.1,44.9
17,PR,41,Paraná,46.3,53.7
18,RJ,33,Rio de Janeiro,45.4,54.6
19,RN,24,Rio Grande do Norte,48.2,51.8
20,RO,11,Rondônia,33.0,67.0
21,RR,14,Roraima,43.4,56.6
22,RS,43,Rio Grande do Sul,47.4,52.6
23,SC,42,Santa Catarina,44.6,55.4
24,SE,28,Sergipe,40.3,59.7
25,SP,35,São Paulo,46.2,53.8
26,TO,17,Tocantins,46.2,53.8

# Juntar tabela

In [18]:
JuncaoAnoscomp = Sem_emprego_2012.merge(Sem_emprego_2026, on=["Sigla", "Código", "Estado"], how="inner")

# Teste junção das Tabelas

In [19]:
JuncaoAnoscomp

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1),Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,45.3,54.7,53.2,46.8
1,AL,27,Alagoas,44.7,55.3,50.7,49.3
2,AM,13,Amazonas,47.5,52.5,46.8,53.2
3,AP,16,Amapá,48.1,51.9,51.1,48.9
4,BA,29,Bahia,43.8,56.2,44.7,55.3
5,CE,23,Ceará,51.1,48.9,52.7,47.3
6,DF,53,Distrito Federal,41.0,59.0,47.9,52.1
7,ES,32,Espírito Santo,46.4,53.6,47.5,52.5
8,GO,52,Goiás,41.0,59.0,47.5,52.5
9,MA,21,Maranhão,47.2,52.8,49.1,50.9
10,MG,31,Minas Gerais,43.1,56.9,48.6,51.4
11,MS,50,Mato Grosso do Sul,47.2,52.8,45.3,54.7
12,MT,51,Mato Grosso,44.1,55.9,42.8,57.2
13,PA,15,Pará,43.2,56.8,48.3,51.7
14,PB,25,Paraíba,44.4,55.6,48.9,51.1
15,PE,26,Pernambuco,43.9,56.1,48.7,51.3
16,PI,22,Piauí,51.2,48.8,55.1,44.9
17,PR,41,Paraná,40.3,59.7,46.3,53.7
18,RJ,33,Rio de Janeiro,44.2,55.8,45.4,54.6
19,RN,24,Rio Grande do Norte,51.0,49.0,48.2,51.8
20,RO,11,Rondônia,43.4,56.6,33.0,67.0
21,RR,14,Roraima,41.8,58.2,43.4,56.6
22,RS,43,Rio Grande do Sul,42.8,57.2,47.4,52.6
23,SC,42,Santa Catarina,42.7,57.3,44.6,55.4
24,SE,28,Sergipe,46.5,53.5,40.3,59.7
25,SP,35,São Paulo,45.4,54.6,46.2,53.8
26,TO,17,Tocantins,55.3,44.7,46.2,53.8